---
- name: Ensure several users exist on origin server
  hosts: m1.origin.test
  become: false
  gather_facts: false
  tasks:
  - name: Generate users list
    ansible.builtin.import_tasks: generate_test_users_data.yml
    run_once: true
    delegate_to: localhost
    vars:
      user_count: 50

  - name: Ensure users are present
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipaadmin_password | default('Secret123') }}"
      users: "{{ user_list }}"
      state: present
...
