# Generate lists for groups
---
- name: Ensure group_cont is set
  ansible.builtin.set_fact:
    group_count: 10
  when: group_count is not defined

- name: Create present services.json data
  ansible.builtin.shell: |
    echo "["
    for i in $(seq -w 1 "{{ group_count }}"); do
        echo "  {"
        echo "    \"name\": \"group_${i}\","
        echo "    \"description\": \"Group Description ${i}\""
        if [ "$i" -lt "{{ group_count }}" ]; then
           echo "  },"
        else
           echo "  }"
        fi
    done
    echo "]"
  register: command

- name: Set group_list
  ansible.builtin.set_fact:
    group_list: "{{ command.stdout | from_json }}"

- name: Set group_absent_list
  ansible.builtin.set_fact:
    group_absent_list: "{{ group_list | map(attribute='name') | list }}"
