---
- name: Local KDC demo recording
  hosts: ab.localkdc.test
  become: false
  gather_facts: false

  tasks:
    - name: Install VHS recorder
      ansible.builtin.shell: |
        dnf -y copr enable abbra/vhs
        dnf -y install vhs

    - name: Copy VHS tape to the target
      ansible.builtin.copy:
        src: tapes/localkdc-demo.tape
        dest: /home/testuser/localkdc-demo.tape
        owner: testuser
        group: testuser
        mode: '0640'

    - name: Record demo
      ansible.builtin.shell: |
        cd /home/testuser
        kdestroy -A
        rm -f .ssh/known_hosts
        vhs localkdc-demo.tape
      become: true
      become_method: su
      become_user: testuser
      become_flags: '-s /bin/bash'

    - name: Fetch recorded video
      ansible.builtin.fetch:
        src: /home/testuser/localkdc-demo.webm
        dest: results/
        flat: true

