- name: Create test environment
  hosts: localhost
  tasks:
    - name: Create container image
      ansible.builtin.shell: |
        podman build -t fedora-freeipa:40 -f Containerfile.build.fedora

    - name: Create Python environment
      ansible.builtin.shell: |
        python3 -m venv venv
      args:
        creates: venv

    - name: Clone and setup mrack
      ansible.builtin.shell: |
        source bin/activate
        pip3 install git+https://github.com/abbra/mrack@podman-freeipa
      args:
        chdir: venv

    - name: Check if ansible-freeipa already downloaded
      stat: path=venv/af
      register: af

    - name: Clone ansible-freeipa repository
      ansible.builtin.shell: |
        git clone --depth 1 https://github.com/freeipa/ansible-freeipa.git af
      args:
        chdir: venv
      when: not af.stat.exists

    - name: Create test environments as podman containers with mrack
      ansible.builtin.shell: |
        source bin/activate
        cp -r ../data .
        cd data
        mrack up -m metadata.yaml
        cp ansible.cfg ..
      args:
        chdir: venv

    - name: Install IPA cluster for ipa1demo.test
      ansible.builtin.shell: |
        ansible-playbook -i data/mrack-inventory.yaml -i data/ipa1demo.hosts \
                         -c podman af/playbooks/install-cluster.yml
      args:
        chdir: venv

    - name: Install IPA cluster for ipa2demo.test
      ansible.builtin.shell: |
        ansible-playbook -i data/mrack-inventory.yaml -i data/ipa2demo.hosts \
                         -c podman af/playbooks/install-cluster.yml
      args:
        chdir: venv

    - name: Establish trust between IPA clusters
      ansible.builtin.shell: |
        ansible-playbook -i data/mrack-inventory.yaml
                         -c podman data/establish-trust.yml
      args:
        chdir: venv


