name: test-ipa-ipa-trust
run-name: Test IPA-IPA trust
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install libkrb5-dev libvirt-dev
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible podman

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Setup ipalab config
        run: |
          python3 -m venv venv
          cd venv
          source bin/activate
          cp -r ../ipalab-config .
          cd ipalab-config
          pip3 install -r requirements.txt
          pip3 install podman-compose

      - name: Update CNI plugins
        working-directory: venv
        run: |
          mkdir cni
          cd cni
          # Determine ARCH for correct release
          export ARCH_CNI=$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)

          # Set to latest release version (https://github.com/containernetworking/plugins/releases)
          export CNI_PLUGIN_VERSION=v1.6.1

          # Grab the latest release version
          curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGIN_VERSION}/cni-plugins-linux-${ARCH_CNI}-${CNI_PLUGIN_VERSION}".tgz

          mkdir plugins
          # Dump the archive
          sudo tar -C plugins -xzf cni-plugins.tgz

          # rename the old plugin folder (location depends on your environment)
          # I am working in wsl Ubuntu
          sudo mv /usr/lib/cni /usr/lib/cni.old

          # replace that broken shiz with some hopefully non-broken shiz
          sudo cp -rf plugins /usr/lib/cni

      - name: Generate containers
        working-directory: venv
        run: |
          source bin/activate
          cd ipalab-config
          ipalab-config -f containerfile-fedora ipalab-idmtoidm-trust.yaml
          podman-compose -f idm2idm-trust/compose.yml up -d --build
          ansible-galaxy collection install -r idm2idm-trust/requirements.yml

      - name: Create IPA deployments
        working-directory: venv
        run: |
          source bin/activate
          cd ipalab-config
          ansible-playbook -i idm2idm-trust/inventory.yml idm2idm-trust/playbooks/install-cluster.yml

      - name: Establish trust between IPA deployments
        working-directory: venv
        run: |
          source bin/activate
          cd ipalab-config
          ansible-galaxy collection install ansible.posix
          ansible-playbook -i idm2idm-trust/inventory.yml establish-trust.yaml
